const PRODUCTS = [
 {name:'A-Frame House Kit',category:'architectural-models',price:'$68.00',description:'A clean architectural study for building a compact modern house model.',meta:'124 pieces · Beginner',image:'assets/images/products/architectural_house.jpg'},
 {name:'Bridge Structure Kit',category:'structural-kits',price:'$84.00',description:'Build a graceful span with layered supports, deck pieces and a detailed arch.',meta:'186 pieces · Intermediate',image:'assets/images/products/bridge.jpg'},
 {name:'City Block Study Set',category:'building-sets',price:'$72.00',description:'Modular forms for composing streets, facades and compact urban studies.',meta:'210 pieces · Beginner',image:'assets/images/products/city_blocks.jpg'},
 {name:'Modern Gallery Model',category:'architectural-models',price:'$96.00',description:'A refined gallery-scale model with clean volumes and presentation base.',meta:'158 pieces · Intermediate',image:'assets/images/products/advanced.jpg'},
 {name:'Miniature Room Set',category:'miniature-world',price:'$44.00',description:'Create a small interior scene with furniture, walls and display details.',meta:'96 pieces · Beginner',image:'assets/images/products/room.jpg'},
 {name:'Miniature Furniture Pack',category:'miniature-world',price:'$32.00',description:'Scale furniture pieces for interiors, studios and architectural scenes.',meta:'48 pieces · Beginner',image:'assets/images/products/furniture.jpg'},
 {name:'Landscape & Scenery Set',category:'miniature-world',price:'$39.00',description:'Trees, terrain and scenic elements for completing a miniature environment.',meta:'72 pieces · Beginner',image:'assets/images/products/scenery.jpg'},
 {name:'Precision Maker Toolkit',category:'maker-tools',price:'$58.00',description:'A compact precision toolkit for assembly, measuring and model finishing.',meta:'18 tools · All levels',image:'assets/images/products/toolkit.jpg'},
 {name:'Finishing Paint Studio',category:'finishing',price:'$36.00',description:'A neutral finishing palette for architectural surfaces and miniature details.',meta:'8 colors · Beginner',image:'assets/images/products/paint.jpg'},
 {name:'Display Presentation Base',category:'display',price:'$42.00',description:'A clean presentation base designed to elevate finished architectural models.',meta:'1 display base · 12×16 in',image:'assets/images/products/display.jpg'},
 {name:'Starter Builder Set',category:'building-sets',price:'$49.00',description:'An approachable first collection of modular pieces for open-ended building.',meta:'140 pieces · Beginner',image:'assets/images/products/starter.jpg'},
 {name:'Tower Study Kit',category:'structural-kits',price:'$78.00',description:'Explore vertical structure, repetition and proportion with a compact tower study.',meta:'132 pieces · Intermediate',image:'assets/images/products/tower.jpg'}
];
let cart=JSON.parse(localStorage.getItem('brick-form-cart')||'[]');
function rootPath(){return location.pathname.includes('/pages/')?'../':''}
function saveCart(){localStorage.setItem('brick-form-cart',JSON.stringify(cart));renderCart()}
function addToCart(i){const p=PRODUCTS[i], found=cart.find(x=>x.name===p.name);if(found)found.qty++;else cart.push({...p,qty:1});saveCart();openCart()}
function removeFromCart(i){cart.splice(i,1);saveCart()}
function openCart(){document.querySelector('#drawer')?.classList.add('open')}
function closeCart(){document.querySelector('#drawer')?.classList.remove('open')}
function closeModal(){document.querySelector('#modal')?.classList.remove('open')}
function renderCart(){const el=document.querySelector('#cartItems');if(!el)return;const root=rootPath();el.innerHTML=cart.length?cart.map((p,i)=>`<div class="cartItem"><img src="${root}${p.image}" alt="${p.name}"><div><strong>${p.name}</strong><div>${p.price} × ${p.qty}</div></div><button onclick="removeFromCart(${i})">×</button></div>`).join(''):'<p class="muted">Your bag is empty.</p>';const n=cart.reduce((a,x)=>a+x.qty,0);document.querySelectorAll('#count').forEach(x=>x.textContent=n)}
function quickView(i){const p=PRODUCTS[i],root=rootPath();document.querySelector('#modalContent').innerHTML=`<img src="${root}${p.image}" alt="${p.name}"><div><div class="eyebrow">${p.category.replaceAll('-',' ')}</div><h2>${p.name}</h2><p>${p.description}</p><div class="price">${p.price}</div><p class="muted">${p.meta}</p><button class="btn" onclick="addToCart(${i});closeModal()">Add to bag</button></div>`;document.querySelector('#modal').classList.add('open')}
function card(p,i){const root=rootPath();return `<article class="card product"><img src="${root}${p.image}" alt="${p.name}" loading="lazy"><div class="copy"><div class="eyebrow">${p.category.replaceAll('-',' ')}</div><h3>${p.name}</h3><p>${p.description}</p><div class="meta">${p.meta}</div><div class="price">${p.price}</div><div class="actions"><button class="add" onclick="addToCart(${i})">Add to bag</button><button class="view" onclick="quickView(${i})">View</button></div></div></article>`}
function renderShop(){const el=document.querySelector('#shopGrid');if(!el)return;const q=(document.querySelector('#search')?.value||'').toLowerCase(),c=document.querySelector('#category')?.value||'';let a=PRODUCTS.filter(p=>(!q||`${p.name} ${p.description}`.toLowerCase().includes(q))&&(!c||p.category===c));const s=document.querySelector('#sort')?.value;if(s==='low')a.sort((x,y)=>parseFloat(x.price.slice(1))-parseFloat(y.price.slice(1)));if(s==='high')a.sort((x,y)=>parseFloat(y.price.slice(1))-parseFloat(x.price.slice(1)));el.innerHTML=a.map(p=>card(p,PRODUCTS.indexOf(p))).join('')}
function renderFeatured(){const el=document.querySelector('#featured');if(el)el.innerHTML=PRODUCTS.slice(0,8).map((p,i)=>card(p,i)).join('')}
document.addEventListener('DOMContentLoaded',()=>{renderFeatured();renderShop();renderCart()})
